# Setup
title:            Jessica Duke
tagline:          'Thejessicaduke'
description:      'Living intentionally'
url:              https://the-jessicaduke.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Jessica Duke'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
